### PR TITLE
Fix setting errorbar color for lines in MPL backend

### LINKED ISSUE #235: Changing line color in superplot via widget does not update the color of the error bars
Screenshot at 2023-08-08 15-53-44

### PR DESCRIPTION
**Pull request by nvaytet**
Fixes #235

### CODE REVIEW

**Comment by jokasimr** [comment]
Looks good to me!

One question though, when I create an errorbar using `plt.errorbar(x, y, s, fmt='none')`  and try to access the hex value of the color using `to_hex(eb.get_children()[0].get_color())` I get the error `ValueError: RGBA sequence should have length 3 or 4`.

I haven't been able to clone the plopp project and run the tests myself, but I guess that doesn't happen there, what's the difference?

**Review by jokasimr — APPROVED** [review]
Looks good to me.

**Comment by jokasimr** [comment]
Could be, I'm on `3.3.2`.

**Comment by nvaytet** [comment]
I think we require `>=3.5` so maybe we are ok?

**Pull request merged**
